# Generated by Django 4.0.3 on 2022-03-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsmeet', '0004_participant_meetups_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='letsmeet.participant'),
        ),
    ]
