# Generated by Django 4.0.3 on 2022-03-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsmeet', '0005_alter_meetups_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetups',
            name='date',
            field=models.DateField(default='2022-06-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetups',
            name='organizer_email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
